### ISSUE TITLE
IAM Role instead of access key and secret for AWS access

### ISSUE THREAD

**Issue by seertenedos** [CitizenPlane/terraform-aws-rabbitmq#4]
Is there a reason to use a access key and secret and not an IAM role for the plugin to access the information it needs for managing the cluster joins etc? Based on the rabbitMQ docs i thought IAM role was supported.

**Comment by Grep-Juub** [comment]
Hey thanks for your interest in this project,

No reason what so ever, this is indeed better with iam role.
I've just followed the example [here](https://www.rabbitmq.com/cluster-formation.html#peer-discovery-aws-credentials) 

Will certainly update this in the future when I can find time to migrate this module to terraform v0.12
